const ApiVersion2 = {
  scenario: {
    detail: `/corporate/scenario/create/`,
    submitInfra: "/corporate/scenario/add-infra/",
    phases: "/corporate/scenario/phases/",
    scenarioList: "/corporate/scenario/list/",
    scenarioDetials: "/corporate/scenario/detail/",
    corporateScenarioInfra: "/corporate/scenario/infra/",
    scenarioStart: "/corporate/scenario/start/",
    getConsole: "scenario/console",
    activegame: "/corporate/scenario/active/",
    getconsole: "/corporate/scenario/console/",
    submitmilestone: "/corporate/scenario/achieve-milestone/",
    switchMachine: "/corporate/scenario/console/switch-machine/",
    toggleFlagLockAdmin: "/corporate/scenario/admin/toggle-flag-lock/",
    toggleMilestoneLockAdmin: "/corporate/scenario/admin/toggle-milestone-lock/",
    togglePhaseLockAdmin: "/corporate/scenario/admin/toggle-phase-lock/",
    whiteTeam: "/corporate/scenario/moderator/",
    console_team: "/corporate/scenario/moderator-console/",
    approved: "/corporate/scenario/approve-milestone/",
    unApproved: "/corporate/scenario/reject-milestone/",
    flag: "/corporate/scenario/submit-flag/",
    hint: "/corporate/scenario/show-hint/",
    ImageAndFal: "v2/scenario/instance/essentials/list/",
    endGame: "/corporate/scenario/delete/",
    white_team_player_other: "/corporate/scenario/moderator-console/detail/",
    getReportList: "corporate/scenario/show-reports/",
    downloadReport: "corporate/scenario/generate-report/",
    newDownloadReport: "corporate/scenario/generate-report/",
    getCategoryCorporate: "corporate/game/based-on-category/",
    liveScore: "/corporate/scenario/active_participants/",
    scenarioWinningWall: `/user/common/winning-wall/corporate`,
    achievers: `/corporate/scenario/achivers/`,
    report_api:'/corporate/scenario/report/',
    walkthroughList: "corporate/scenario/walkthroughs/",
    chatChannels: "/corporate/scenario/chat/channels/",       
    chatMessages: "/corporate/scenario/chat/messages/",        
    chatSend: "/corporate/scenario/chat/send/", 
  },
};

export default ApiVersion2;
